# Generated by Django 4.2.16 on 2024-10-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=16)),
                ('quantity', models.IntegerField()),
                ('buy_price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
